import  javax.swing.Timer;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.ImageIcon;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogIn.java
 *
 * Created on 7 Oct, 2014, 8:44:23 PM
 */

/**
 *
 * @author Varsha Margaret
 */
public class LogIn extends javax.swing.JFrame {

    /** Creates new form LogIn */
    public LogIn() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        F2 = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        l14 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        t15 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        F3 = new javax.swing.JFrame();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        p1 = new javax.swing.JPasswordField();
        p2 = new javax.swing.JPasswordField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        t9 = new javax.swing.JTextArea();
        jButton19 = new javax.swing.JButton();
        F4 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        F5 = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        p3 = new javax.swing.JPasswordField();
        t14 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        F6 = new javax.swing.JFrame();
        jButton20 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        F7 = new javax.swing.JFrame();
        jButton21 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        F8 = new javax.swing.JFrame();
        jButton22 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        F9 = new javax.swing.JFrame();
        jButton23 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        F10 = new javax.swing.JFrame();
        jButton24 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        F11 = new javax.swing.JFrame();
        jButton25 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        F12 = new javax.swing.JFrame();
        jButton26 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        F13 = new javax.swing.JFrame();
        jButton27 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        F14 = new javax.swing.JFrame();
        jButton28 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        F15 = new javax.swing.JFrame();
        jButton29 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        F16 = new javax.swing.JFrame();
        jButton30 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        F17 = new javax.swing.JFrame();
        jButton31 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        F18 = new javax.swing.JFrame();
        jButton32 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        F19 = new javax.swing.JFrame();
        jButton33 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        F20 = new javax.swing.JFrame();
        jButton34 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        F21 = new javax.swing.JFrame();
        jButton35 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        F22 = new javax.swing.JFrame();
        jButton36 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        F23 = new javax.swing.JFrame();
        jButton37 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        F24 = new javax.swing.JFrame();
        jButton38 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        F25 = new javax.swing.JFrame();
        jButton39 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        F26 = new javax.swing.JFrame();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        t20 = new javax.swing.JTextField();
        t21 = new javax.swing.JTextField();
        t22 = new javax.swing.JTextField();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        F27 = new javax.swing.JFrame();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();

        F2.getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Harrington", 1, 36));
        jButton2.setText("Sign Up");
        jButton2.setToolTipText("Use this button for signing in if you are already a member");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton2);
        jButton2.setBounds(619, 20, 250, 51);

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 48));
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Search Based On");
        F2.getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 90, 405, 58);

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Country");
        F2.getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 180, 88, 23);

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 24));
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Year");
        F2.getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 230, 50, 23);

        t1.setFont(new java.awt.Font("Footlight MT Light", 1, 24));
        F2.getContentPane().add(t1);
        t1.setBounds(380, 180, 140, 29);

        t2.setFont(new java.awt.Font("Footlight MT Light", 1, 24));
        F2.getContentPane().add(t2);
        t2.setBounds(380, 230, 140, 29);

        jButton3.setFont(new java.awt.Font("Footlight MT Light", 1, 24));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton3);
        jButton3.setBounds(280, 290, 150, 31);

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 204));

        table1.setFont(new java.awt.Font("Chiller", 1, 22));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNo.", "Crime Name", "Country", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);
        table1.getColumnModel().getColumn(1).setResizable(false);

        F2.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 390, 640, 90);

        jButton4.setFont(new java.awt.Font("Footlight MT Light", 1, 24));
        jButton4.setText("Undo Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton4);
        jButton4.setBounds(520, 290, 230, 31);

        l14.setFont(new java.awt.Font("Viner Hand ITC", 1, 24));
        l14.setForeground(new java.awt.Color(255, 255, 204));
        l14.setText("Enter SNo For More Details On Any Crime");
        F2.getContentPane().add(l14);
        l14.setBounds(10, 550, 497, 39);

        jButton16.setFont(new java.awt.Font("Viner Hand ITC", 1, 24));
        jButton16.setText("Okay");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton16);
        jButton16.setBounds(380, 620, 140, 47);

        t15.setFont(new java.awt.Font("Viner Hand ITC", 1, 24));
        t15.setForeground(new java.awt.Color(255, 255, 204));
        F2.getContentPane().add(t15);
        t15.setBounds(570, 550, 190, 40);

        jButton18.setFont(new java.awt.Font("Viner Hand ITC", 1, 24));
        jButton18.setText("Back");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton18);
        jButton18.setBounds(660, 620, 160, 47);

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Photos (Margaret)\\Project Pictures\\CAD\\skynews.img.1200.745.jpeg")); // NOI18N
        jLabel33.setText("jLabel33");
        jLabel33.setMaximumSize(new java.awt.Dimension(1032, 774));
        jLabel33.setPreferredSize(new java.awt.Dimension(1032, 774));
        F2.getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 1400, 750);

        l1.setFont(new java.awt.Font("Chiller", 1, 24));
        l1.setText("First Name");

        l2.setFont(new java.awt.Font("Chiller", 1, 24));
        l2.setText("Last Name");

        l3.setFont(new java.awt.Font("Chiller", 1, 24));
        l3.setText("Date Of Birth(yyyymmdd)");

        l4.setFont(new java.awt.Font("Chiller", 1, 24));
        l4.setText("Gender(F/M)");

        l5.setFont(new java.awt.Font("Chiller", 1, 24));
        l5.setText("Passport No.");

        l6.setFont(new java.awt.Font("Chiller", 1, 24));
        l6.setText("Mobile No.");

        l7.setFont(new java.awt.Font("Chiller", 1, 24));
        l7.setText("Job In Detail");

        l8.setFont(new java.awt.Font("Chiller", 1, 24));
        l8.setText("Address");

        l9.setFont(new java.awt.Font("Chiller", 1, 24));
        l9.setText("Age");

        l10.setFont(new java.awt.Font("Chiller", 1, 24));
        l10.setText("Driving License");

        l11.setFont(new java.awt.Font("Chiller", 1, 24));
        l11.setText("Username");

        l12.setFont(new java.awt.Font("Chiller", 1, 24));
        l12.setText("Password");

        l13.setFont(new java.awt.Font("Chiller", 1, 24));
        l13.setText("Confrm Password");

        t3.setFont(new java.awt.Font("Chiller", 1, 22));

        t4.setFont(new java.awt.Font("Chiller", 1, 22));

        t5.setFont(new java.awt.Font("Chiller", 1, 22));

        t6.setFont(new java.awt.Font("Chiller", 1, 22));
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        t7.setFont(new java.awt.Font("Chiller", 1, 22));
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        t8.setFont(new java.awt.Font("Chiller", 1, 22));

        t11.setFont(new java.awt.Font("Chiller", 1, 22));

        t12.setFont(new java.awt.Font("Chiller", 1, 22));

        t13.setFont(new java.awt.Font("Chiller", 1, 22));
        t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t13ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Chiller", 1, 36));
        jButton5.setText("Sign Up");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Chiller", 1, 36));
        jButton6.setText("Sign In");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Chiller", 1, 22));
        ta1.setRows(5);
        jScrollPane2.setViewportView(ta1);

        p1.setFont(new java.awt.Font("Chiller", 1, 22));

        p2.setFont(new java.awt.Font("Chiller", 1, 22));

        jButton7.setFont(new java.awt.Font("Chiller", 1, 36));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Chiller", 1, 36));
        jButton8.setText("Clear All");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
              });

        jButton9.setFont(new java.awt.Font("Chiller", 1, 36));
        jButton9.setText("Log In");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        t9.setColumns(20);
        t9.setFont(new java.awt.Font("Chiller", 1, 22));
        t9.setRows(5);
        jScrollPane3.setViewportView(t9);

        jButton19.setFont(new java.awt.Font("Chiller", 1, 36));
        jButton19.setText("Exit");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout F3Layout = new javax.swing.GroupLayout(F3.getContentPane());
        F3.getContentPane().setLayout(F3Layout);
        F3Layout.setHorizontalGroup(
            F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(F3Layout.createSequentialGroup()
                .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(F3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(l1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                            .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(l7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(jButton8))
                            .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(F3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(F3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(t4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t8, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(165, 165, 165)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, F3Layout.createSequentialGroup()
                                .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(F3Layout.createSequentialGroup()
                                        .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(l9, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(l10, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(l11, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addGroup(F3Layout.createSequentialGroup()
                                            .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                .addGap(5, 5, 5)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t13, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(t12, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(t11, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addGroup(F3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, F3Layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(282, 282, 282)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401))
        );
        F3Layout.setVerticalGroup(
            F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(F3Layout.createSequentialGroup()
                .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(F3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6)
                        .addGap(66, 66, 66)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l8)
                            .addComponent(l1)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2))
                        .addGap(34, 34, 34)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l9)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l3))
                        .addGap(35, 35, 35)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l10)
                            .addComponent(l4)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l11)
                            .addComponent(l5)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l12)
                            .addComponent(l6)
                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(F3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(F3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l13)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(F3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(l7)))
                .addGap(74, 74, 74)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(54, 54, 54)
                .addGroup(F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(jButton7))
                .addContainerGap(147, Short.MAX_VALUE))
        );
 F4.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 48));
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Welcome");
        F4.getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 140, 208, 74);

        jButton10.setFont(new java.awt.Font("Gabriola", 1, 18));
        jButton10.setText("View Current Status");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        F4.getContentPane().add(jButton10);
        jButton10.setBounds(50, 370, 240, 39);

        jButton11.setFont(new java.awt.Font("Gabriola", 1, 18));
        jButton11.setText("Search Information");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        F4.getContentPane().add(jButton11);
        jButton11.setBounds(360, 370, 230, 39);

        jButton12.setFont(new java.awt.Font("Gabriola", 1, 18));
        jButton12.setText("Enter New Report");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        F4.getContentPane().add(jButton12);
        jButton12.setBounds(647, 370, 220, 39);

        jButton17.setFont(new java.awt.Font("Gabriola", 1, 18));
        jButton17.setText("Back");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        F4.getContentPane().add(jButton17);
        jButton17.setBounds(410, 530, 150, 39);

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Photos (Margaret)\\Project Pictures\\CAD\\rsz_all-hands-on-deck-stop-the-abuse.jpg")); // NOI18N
        jLabel34.setText("jLabel34");
        jLabel34.setMaximumSize(new java.awt.Dimension(1280, 853));
        jLabel34.setPreferredSize(new java.awt.Dimension(1280, 853));
        F4.getContentPane().add(jLabel34);
        jLabel34.setBounds(0, 0, 1280, 850);

        F5.getContentPane().setLayout(null);

        ta2.setColumns(20);
        ta2.setFont(new java.awt.Font("Chiller", 1, 22));
        ta2.setForeground(new java.awt.Color(51, 51, 51));
        ta2.setRows(5);
        jScrollPane4.setViewportView(ta2);

        F5.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(390, 230, 470, 340);

        jLabel5.setFont(new java.awt.Font("Chiller", 1, 24));
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("You Can Safely Store Your Informtion Here");
        F5.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 320, 350, 30);

        jLabel6.setFont(new java.awt.Font("Chiller", 1, 24));
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Username");
        F5.getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 60, 72, 29);

        jLabel7.setFont(new java.awt.Font("Chiller", 1, 24));
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Password");
        F5.getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 150, 67, 29);

        p3.setFont(new java.awt.Font("Chiller", 1, 24));
        F5.getContentPane().add(p3);
        p3.setBounds(390, 160, 190, 35);

        t14.setFont(new java.awt.Font("Chiller", 1, 24));
        t14.setForeground(new java.awt.Color(51, 51, 51));
        t14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t14ActionPerformed(evt);
            }
        });
        F5.getContentPane().add(t14);
        t14.setBounds(390, 60, 190, 35);

        jButton13.setFont(new java.awt.Font("Chiller", 1, 24));
        jButton13.setText("Update");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        F5.getContentPane().add(jButton13);
        jButton13.setBounds(70, 610, 120, 37);

        jButton14.setFont(new java.awt.Font("Chiller", 1, 24));
        jButton14.setText("Back");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        F5.getContentPane().add(jButton14);
        jButton14.setBounds(760, 620, 110, 37);

        jButton15.setFont(new java.awt.Font("Chiller", 1, 24));
        jButton15.setText("Retrieve Saved Data");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        F5.getContentPane().add(jButton15);
        jButton15.setBounds(400, 700, 240, 37);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ItsTimeWeStoppedHidingChildAbuseFAC.jpg"))); // NOI18N
        jLabel35.setText("jLabel35");
        jLabel35.setMaximumSize(new java.awt.Dimension(900, 1200));
        jLabel35.setPreferredSize(new java.awt.Dimension(900, 1200));
        F5.getContentPane().add(jLabel35);
        jLabel35.setBounds(0, 0, 900, 1200);

        F6.getContentPane().setLayout(null);

        jButton20.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton20.setText("Back");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        F6.getContentPane().add(jButton20);
        jButton20.setBounds(590, 660, 110, 39);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(new java.awt.Dimension(1438, 749));
        jLabel8.setPreferredSize(new java.awt.Dimension(1438, 749));
        F6.getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1438, 750);

        F7.getContentPane().setLayout(null);

        jButton21.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton21.setText("Back");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        F7.getContentPane().add(jButton21);
        jButton21.setBounds(640, 370, 120, 39);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setMaximumSize(new java.awt.Dimension(1439, 442));
        jLabel9.setPreferredSize(new java.awt.Dimension(1439, 442));
        F7.getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1440, 440);

        F8.getContentPane().setLayout(null);

        jButton22.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton22.setText("Back");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        F8.getContentPane().add(jButton22);
        jButton22.setBounds(480, 510, 110, 39);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/13.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setMaximumSize(new java.awt.Dimension(1044, 569));
        jLabel10.setPreferredSize(new java.awt.Dimension(1044, 569));
        F8.getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1040, 570);

        F9.getContentPane().setLayout(null);

        jButton23.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton23.setText("Back");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        F9.getContentPane().add(jButton23);
        jButton23.setBounds(440, 510, 140, 39);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/14.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setMaximumSize(new java.awt.Dimension(1032, 569));
        jLabel11.setPreferredSize(new java.awt.Dimension(1032, 569));
        F9.getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1030, 570);

        F10.getContentPane().setLayout(null);

        jButton24.setFont(new java.awt.Font("Brush Script MT", 3, 24));
        jButton24.setText("Back");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        F10.getContentPane().add(jButton24);
        jButton24.setBounds(829, 29, 110, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/15.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.setMaximumSize(new java.awt.Dimension(1037, 742));
        jLabel12.setPreferredSize(new java.awt.Dimension(1037, 742));
        F10.getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 10, 1037, 740);

        F11.getContentPane().setLayout(null);

        jButton25.setFont(new java.awt.Font("Brush Script MT", 3, 24));
        jButton25.setText("Back");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        F11.getContentPane().add(jButton25);
        jButton25.setBounds(760, 10, 90, 39);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setMaximumSize(new java.awt.Dimension(1033, 711));
        jLabel13.setPreferredSize(new java.awt.Dimension(1033, 711));
        F11.getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1033, 710);

        F12.getContentPane().setLayout(null);

        jButton26.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton26.setText("Back");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        F12.getContentPane().add(jButton26);
        jButton26.setBounds(400, 390, 130, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Photos (Margaret)\\Project Pictures\\17.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setMaximumSize(new java.awt.Dimension(1032, 457));
        jLabel14.setPreferredSize(new java.awt.Dimension(1032, 457));
        F12.getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 0, 1030, 457);

        F13.getContentPane().setLayout(null);

        jButton27.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton27.setText("Back");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        F13.getContentPane().add(jButton27);
        jButton27.setBounds(800, 10, 90, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Photos (Margaret)\\Project Pictures\\18.jpg")); // NOI18N
        jLabel15.setText("jLabel15");
        jLabel15.setMaximumSize(new java.awt.Dimension(1047, 375));
        jLabel15.setPreferredSize(new java.awt.Dimension(1047, 375));
        F13.getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1040, 370);

        F14.getContentPane().setLayout(null);

        jButton28.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton28.setText("Back");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        F14.getContentPane().add(jButton28);
        jButton28.setBounds(390, 400, 110, 39);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/19.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.setMaximumSize(new java.awt.Dimension(1039, 484));
        jLabel16.setPreferredSize(new java.awt.Dimension(1039, 484));
        F14.getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 1040, 480);

        F15.getContentPane().setLayout(null);

        jButton29.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton29.setText("Back");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        F15.getContentPane().add(jButton29);
        jButton29.setBounds(360, 500, 110, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Photos (Margaret)\\Project Pictures\\a (2).jpg")); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.setMaximumSize(new java.awt.Dimension(1002, 485));
        jLabel17.setPreferredSize(new java.awt.Dimension(1002, 485));
        F15.getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 1000, 590);

        F16.getContentPane().setLayout(null);

        jButton30.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton30.setText("Back");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        F16.getContentPane().add(jButton30);
        jButton30.setBounds(400, 373, 110, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.setMaximumSize(new java.awt.Dimension(998, 512));
        jLabel18.setPreferredSize(new java.awt.Dimension(998, 512));
        F16.getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 998, 510);

        F17.getContentPane().setLayout(null);

        jButton31.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton31.setText("Back");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        F17.getContentPane().add(jButton31);
        jButton31.setBounds(810, 20, 90, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jLabel19.setMaximumSize(new java.awt.Dimension(985, 590));
        jLabel19.setPreferredSize(new java.awt.Dimension(985, 590));
        F17.getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 985, 590);

        F18.getContentPane().setLayout(null);

        jButton32.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton32.setText("Back");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        F18.getContentPane().add(jButton32);
        jButton32.setBounds(760, 20, 120, 39);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        jLabel20.setMaximumSize(new java.awt.Dimension(997, 581));
        jLabel20.setPreferredSize(new java.awt.Dimension(997, 581));
        F18.getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 997, 580);

        F19.getContentPane().setLayout(null);

        jButton33.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton33.setText("Back");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        F19.getContentPane().add(jButton33);
        jButton33.setBounds(350, 440, 100, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jLabel21.setMaximumSize(new java.awt.Dimension(999, 580));
        jLabel21.setPreferredSize(new java.awt.Dimension(999, 580));
        F19.getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 1000, 580);

        F20.getContentPane().setLayout(null);

        jButton34.setFont(new java.awt.Font("Blackadder ITC", 3, 36));
        jButton34.setText("Back");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        F20.getContentPane().add(jButton34);
        jButton34.setBounds(840, 10, 109, 53);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g.jpg"))); // NOI18N
        jLabel22.setText("jLabel22");
        jLabel22.setMaximumSize(new java.awt.Dimension(995, 625));
        jLabel22.setPreferredSize(new java.awt.Dimension(995, 625));
        F20.getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 995, 620);

        F21.getContentPane().setLayout(null);

        jButton35.setFont(new java.awt.Font("Blackadder ITC", 3, 36));
        jButton35.setText("Back");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        F21.getContentPane().add(jButton35);
        jButton35.setBounds(800, 10, 109, 53);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h.jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        jLabel23.setMaximumSize(new java.awt.Dimension(974, 618));
        jLabel23.setPreferredSize(new java.awt.Dimension(974, 618));
        F21.getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 974, 620);

        F22.getContentPane().setLayout(null);

        jButton36.setFont(new java.awt.Font("Blackadder ITC", 3, 36));
        jButton36.setText("Back");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        F22.getContentPane().add(jButton36);
        jButton36.setBounds(430, 410, 109, 53);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i.jpg"))); // NOI18N
        jLabel24.setText("jLabel24");
        jLabel24.setMaximumSize(new java.awt.Dimension(1036, 484));
        jLabel24.setPreferredSize(new java.awt.Dimension(1036, 484));
        F22.getContentPane().add(jLabel24);
        jLabel24.setBounds(-10, -10, 1030, 500);

        F23.getContentPane().setLayout(null);

        jButton37.setFont(new java.awt.Font("Blackadder ITC", 3, 36));
        jButton37.setText("Back");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
          F23.getContentPane().add(jButton37);
        jButton37.setBounds(830, 10, 109, 53);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j.jpg"))); // NOI18N
        jLabel25.setText("jLabel25");
        jLabel25.setMaximumSize(new java.awt.Dimension(1034, 741));
        jLabel25.setPreferredSize(new java.awt.Dimension(1034, 741));
        F23.getContentPane().add(jLabel25);
        jLabel25.setBounds(10, 0, 1030, 760);

        F24.getContentPane().setLayout(null);

        jButton38.setFont(new java.awt.Font("Blackadder ITC", 3, 24));
        jButton38.setText("Back");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        F24.getContentPane().add(jButton38);
        jButton38.setBounds(450, 570, 83, 39);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/k.jpg"))); // NOI18N
        jLabel26.setText("jLabel26");
        jLabel26.setMaximumSize(new java.awt.Dimension(1033, 619));
        jLabel26.setPreferredSize(new java.awt.Dimension(1033, 619));
        F24.getContentPane().add(jLabel26);
        jLabel26.setBounds(0, -30, 1030, 680);

        F25.getContentPane().setLayout(null);

        jButton39.setFont(new java.awt.Font("Blackadder ITC", 1, 36));
        jButton39.setText("Back");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        F25.getContentPane().add(jButton39);
        jButton39.setBounds(410, 450, 150, 50);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/l.jpg"))); // NOI18N
        jLabel27.setText("jLabel27");
        jLabel27.setMaximumSize(new java.awt.Dimension(1043, 546));
        jLabel27.setPreferredSize(new java.awt.Dimension(1043, 546));
        F25.getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 1040, 540);

        F26.getContentPane().setLayout(null);

        jLabel28.setFont(new java.awt.Font("Harrington", 1, 24));
        jLabel28.setText("Crime Name");
        F26.getContentPane().add(jLabel28);
        jLabel28.setBounds(200, 140, 137, 29);

        jLabel29.setFont(new java.awt.Font("Harrington", 1, 24));
        jLabel29.setText("Country");
        F26.getContentPane().add(jLabel29);
        jLabel29.setBounds(220, 230, 93, 29);

        jLabel30.setFont(new java.awt.Font("Harrington", 1, 24));
        jLabel30.setText("Year");
        F26.getContentPane().add(jLabel30);
        jLabel30.setBounds(260, 320, 54, 29);

        t20.setFont(new java.awt.Font("Harrington", 0, 18));
        F26.getContentPane().add(t20);
        t20.setBounds(470, 140, 130, 28);

        t21.setFont(new java.awt.Font("Harrington", 0, 18));
        F26.getContentPane().add(t21);
        t21.setBounds(470, 230, 130, 28);

        t22.setFont(new java.awt.Font("Harrington", 0, 18));
        F26.getContentPane().add(t22);
        t22.setBounds(470, 320, 130, 28);

        jButton40.setFont(new java.awt.Font("Harrington", 1, 24));
        jButton40.setText("Continue");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        F26.getContentPane().add(jButton40);
        jButton40.setBounds(350, 520, 190, 37);

        jButton41.setFont(new java.awt.Font("Harrington", 1, 24));
        jButton41.setText("Back");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        F26.getContentPane().add(jButton41);
        jButton41.setBounds(590, 470, 150, 37);

        jButton42.setFont(new java.awt.Font("Harrington", 1, 24));
        jButton42.setText("Clear All");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        F26.getContentPane().add(jButton42);
        jButton42.setBounds(100, 490, 180, 37);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tanmyait-2.jpg"))); // NOI18N
        jLabel36.setText("jLabel36");
        jLabel36.setMaximumSize(new java.awt.Dimension(1100, 733));
        jLabel36.setPreferredSize(new java.awt.Dimension(1100, 733));
        F26.getContentPane().add(jLabel36);
        jLabel36.setBounds(0, 0, 1100, 733);

        F27.getContentPane().setLayout(null);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CHAMPION-OF-CHILDREN-FINALLogo1.jpg"))); // NOI18N
        jLabel32.setMaximumSize(new java.awt.Dimension(1221, 779));
        jLabel32.setPreferredSize(new java.awt.Dimension(1221, 779));
        F27.getContentPane().add(jLabel32);
        jLabel32.setBounds(0, 0, 1150, 1080);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Chiller", 1, 36));
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 390, 180, 51);

        jButton43.setFont(new java.awt.Font("Chiller", 1, 36));
        jButton43.setText("About Us");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton43);
        jButton43.setBounds(540, 390, 160, 51);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/childabuse.jpg"))); // NOI18N
        getContentPane().add(jLabel31);
        jLabel31.setBounds(0, 0, 1000, 870);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
F2.setSize(1200,750 );
        F2.setVisible(true);
l14.setVisible(false);
jButton16.setVisible(false);
t15.setVisible(false);
jButton18.setVisible(false);



        // TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
String a=t1.getText();
String b= t2.getText();
if(a.isEmpty() && b.isEmpty())
    JOptionPane.showMessageDialog(this,"Enter Country Or Year");
DefaultTableModel model= (DefaultTableModel)
        table1.getModel();
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=(Connection)
     DriverManager.getConnection("jdbc:mysql://localhost:3306/cad","root","mysql");
Statement stmt=(Statement) con.createStatement();
String query= "Select * from sort where country='"+a+"' or Year='"+b+"' ;";
ResultSet rs=stmt.executeQuery(query);
while(rs.next())
{String Sno=rs.getString("Sno");
 String Crime=rs.getString("Crime_Name");
 String Country=rs.getString("Country");
 String Year=rs.getString("Year");
 model.addRow(new Object[] {Sno,Crime,Country,Year});}}
 catch(Exception e)
 {JOptionPane.showMessageDialog(null, e.getMessage());
} // TODO add your handling code here:
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); //To remove All Rows From Current Model
}}// TODO add your handling code here:
    }                                        

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void t13ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
F3.setSize(1400, 900);
F3.setVisible(true);
jButton7.setVisible(false);
jButton9.setVisible(false);
jButton19.setVisible(false);
        // TODO add your handling code here:
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         

String s=t3.getText();
String l=t4.getText();
String d=t5.getText();
String g=t6.getText();
String p=t7.getText();
String m=t8.getText();
String j=t9.getText();
String a=ta1.getText();
String e=t11.getText();
String n=t12.getText();
String u=t13.getText();
String ps=p1.getText();
String ps2=p2.getText();
Integer x = Integer.valueOf(e); // used to return the number value of the string 'e' and store it in variable 'x'
Integer y= Integer.valueOf(d);
if(s.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your First Name");

else if(l.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your Last Name");
else if(d.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your Date Of Birth");
else if(g.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your Gender");
else if(p.length()==0)

   JOptionPane.showMessageDialog(this,"Please enter Your Passport Number");
else if(n.length()==0)

   JOptionPane.showMessageDialog(this,"Please enter Your Driver's Licence");

else if(m.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your Mobile Number");
else if(j.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your Job");
else if(a.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your Address");
else if(e.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your Age");
else if(u.length()==0)
   JOptionPane.showMessageDialog(this,"Please enter Your UserName");
else if(x<27)
 JOptionPane.showMessageDialog(this,"You Are Not Eligible TO be A Member As You Are Do Not Come Under The Specified Age Limit ");
else if(m.length()<10)
    JOptionPane.showMessageDialog(this,"Please enter Valid Mobile Number");


 else if(y>19891231){
 
   JOptionPane.showMessageDialog(this,"You Are Not Eligible TO be A Member As You Are Do Not Come Under The Specified Age Limit ");
   
        }
 else if(ps.length()==0)
     JOptionPane.showMessageDialog(this, "Please Enter Password");
else
{
    if(ps.equals(ps2))
    {try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=(Connection)
     DriverManager.getConnection("jdbc:mysql://localhost:3306/cad","root","mysql");
Statement stmt=(Statement) con.createStatement();
String query="insert into sign_up values('"+s+"','"+l+"','"+d+"','"+g+"','"+p+"','"+m+"','"+j+"','"+a+"','"+e+"','"+n+"','"+u+"','"+ps+"');";
String query2="insert into profile values('"+u+"',null,'"+ps+"');";
stmt.executeUpdate(query);
     stmt.executeUpdate(query2);}
     catch(Exception f)
 {JOptionPane.showMessageDialog(null, f.getMessage());

}
}else
    JOptionPane.showMessageDialog(this, "Your Passwords Do NOT Match, Please try Again");

jButton9.setVisible(false);














}








        // TODO add your handling code here:
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
l1.setVisible(false);
l2.setVisible(false);
l3.setVisible(false);
l4.setVisible(false);
l5.setVisible(false);
l6.setVisible(false);
l7.setVisible(false);
l8.setVisible(false);
l9.setVisible(false);
l10.setVisible(false);
l13.setVisible(false);
t3.setVisible(false);
t4.setVisible(false);
t5.setVisible(false);
t6.setVisible(false);
t7.setVisible(false);
t8.setVisible(false);
t9.setVisible(false);
ta1.setVisible(false);
t11.setVisible(false);
t12.setVisible(false);
jButton5.setVisible(false);
jButton7.setVisible(true);
jScrollPane2.setVisible(false);
p2.setVisible(false);
jButton9.setVisible(true);
jScrollPane3.setVisible(false);







        // TODO add your handling code here:
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
l1.setVisible(true);
l2.setVisible(true);
l3.setVisible(true);
l4.setVisible(true);
l5.setVisible(true);
l6.setVisible(true);
l7.setVisible(true);
l8.setVisible(true);
l9.setVisible(true);
l10.setVisible(true);
t3.setVisible(true);
t4.setVisible(true);
t5.setVisible(true);
t6.setVisible(true);
t7.setVisible(true);
t8.setVisible(true);
t9.setVisible(true);
ta1.setVisible(true);
t11.setVisible(true);
t12.setVisible(true);
p2.setVisible(true);
jButton5.setVisible(true);
jButton7.setVisible(false);
p1.setText("");
t13.setText("");
jButton19.setVisible(true);
jButton9.setVisible(false);
jScrollPane3.setVisible(true);
jScrollPane2.setVisible(true);


l13.setVisible(true);






        // TODO add your handling code here:
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
t3.setText("");
t4.setText("");
  t5.setText("");
  t6.setText("");
  t7.setText("");
  t6.setText("");
  t9.setText("");
  ta1.setText("");
     t11.setText("");
        t12.setText("");
        t13.setText("");
        p1.setText("");
        p2.setText("");

        // TODO add your handling code here:
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
String u=t13.getText();
String p=p1.getText();
if(u.length()==0){
JOptionPane.showMessageDialog(this, "Please Enter Your Username");
}
else if(p.length()==0)
    JOptionPane.showMessageDialog(this, "Please Enter Your Password");
else{
    try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=(Connection)
     DriverManager.getConnection("jdbc:mysql://localhost:3306/cad","root","mysql");
Statement stmt=(Statement) con.createStatement();
String query="select username, password from sign_up where username='"+u+"' and password='"+p+"';";
ResultSet rs=stmt.executeQuery(query);
if(rs.next())
{
    String username = rs.getString("username");
    String password = rs.getString("password");
    F4.setVisible(true);
    F4.setSize(1280, 853);
}
else
    JOptionPane.showMessageDialog(this, "Access Denied- Please Try Again");
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }


























}
        // TODO add your handling code here:
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F5.setVisible(true);
F5.setSize(900, 1200);












        // TODO add your handling code here:
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
String u= t14.getText();
String p= p3.getText();
String r= ta2.getText();
if(u.length()==0)
    JOptionPane.showMessageDialog(this, "Please Enter Your Username");
else if (p.length()==0)
    JOptionPane.showMessageDialog(this, "Please Enter Your Password");
else if (r.length()==0)
    JOptionPane.showMessageDialog(this, "No Data For Updation");
else{
 try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=(Connection)
     DriverManager.getConnection("jdbc:mysql://localhost:3306/cad","root","mysql");
Statement stmt=(Statement) con.createStatement();
String query="update profile set crime_details='"+r+"'where username='"+u+"' and password='"+p+"';";
stmt.executeUpdate(query);
 }
 catch (Exception e)
 {
     JOptionPane.showMessageDialog(this, e.getMessage());
 }
}
 // TODO add your handling code here:
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F4.setSize(1400, 900);
        F4.setVisible(true);
t14.setText("");
p3.setText("");
ta2.setText("");

// TODO add your handling code here:
    }                                         

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
String u= t14.getText();
String p= p3.getText();
if(u.length()==0)
    JOptionPane.showMessageDialog(this, "Please Enter Your Username");
else if (p.length()==0)
    JOptionPane.showMessageDialog(this, "Please Enter Your Password");
else{
    try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=(Connection)
     DriverManager.getConnection("jdbc:mysql://localhost:3306/cad","root","mysql");
Statement stmt=(Statement) con.createStatement();
String query="select crime_details from profile where username='"+u+"' and password='"+p+"';";
ResultSet rs=stmt.executeQuery(query);
if(rs.next()){
    String crime = rs.getString("crime_details");
    ta2.setText(""+ crime);
}
else
    JOptionPane.showMessageDialog(this, "Sorry!! No Match Found");





}
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

}



        // TODO add your handling code here:
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1200, 745);
        F2.setVisible(true);
jButton2.setVisible(false);

jButton18.setVisible(true);
l14.setVisible(true);
t15.setVisible(true);
jButton16.setVisible(true);






        // TODO add your handling code here:
    }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        F3.setSize(1400, 900);
        F3.setVisible(true);      // TODO add your handling code here:
t13.setText("");
p1.setText("");
    }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F4.setVisible(true);
F4.setSize(1400, 900);

t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++)

model.removeRow(0); }//To remove All Rows From Current Model
// TODO add your handling code here:
    }                                         

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          
System.exit(0);        // TODO add your handling code here:
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
String z= t15.getText();
Integer y= Integer.valueOf(z);
if(z.length()==0)
    JOptionPane.showMessageDialog(this, "Please enter Corresponding SNo Of The Required Crime In The Table");
else if(y==1){
F6.setVisible(true);
F6.setSize(1440,800);}
else if(y==9){
    F7.setVisible(true);
F7.setSize(1439,444);}
else if(y==7){
    F8.setVisible(true);
    F8.setSize(1044,570);}
else if(y==5){
    F9.setSize(1032,570);
    F9.setVisible(true);}
else if(y==11){
    F10.setVisible(true);
F10.setSize(1037,744);}
else if(y==6){
    F11.setVisible(true);
F11.setSize(1033,713);}
else if(y==12){
   F12.setVisible(true);
F12.setSize(1032,460);}
else if(y==8){
F13.setSize(1047,378);
    F13.setVisible(true);}
else if(y==13){
   F14.setSize(1039,485);
    F14.setVisible(true);}
else if(y==20){
   F15.setSize(1002,588);
    F15.setVisible(true);}
else if(y==19){
    F16.setSize(998,515);
    F16.setVisible(true);}
else if(y==18){
    F17.setSize(985,594);
    F17.setVisible(true);}
else if(y==17){
    F18.setSize(997,585);
    F18.setVisible(true);}
else if(y==16){
    F19.setSize(999,585);
    F19.setVisible(true);}
else if(y==15){
    F20.setSize(995,624);
    F20.setVisible(true);}
else if(y==14){
    F21.setSize(974,6120);
    F21.setVisible(true);}
else if(y==4){
    F22.setSize(1036,485);
    F22.setVisible(true);}
else if(y==3){
    F23.setSize(1034,755);
    F23.setVisible(true);}
else if(y==2){
    F24.setSize(1033,695);
    F24.setVisible(true);}
else if(y==10){
    F25.setSize(1043,550);
    F25.setVisible(true);}
// TODO add your handling code here:
    }                                         

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setVisible(true);
F2.setSize(1400, 900);
        t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++)

model.removeRow(0); }



        // TODO add your handling code here:
    }                                         

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}       // TODO add your handling code here:
    }                                         

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}       // TODO add your handling code here:
    // TODO add your handling code here:
    }                                         

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}
// TODO add your handling code here:
    }                                         

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
        t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}            // TODO add your handling code here:
    }                                         

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}            // TODO add your handling code here:
    }                                         

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);  t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}          // TODO add your handling code here:
    }                                         

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        F2.setSize(1400, 900);F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F2.setSize(1400, 900);
        F2.setVisible(true);
t1.setText("");
t2.setText("");
DefaultTableModel model = (DefaultTableModel)
        table1.getModel();
int rows=model.getRowCount();
if(rows>0){
for (int i=0; i<rows; i++){
t15.setText("");
model.removeRow(0); }}    // TODO add your handling code here:
    }                                         

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F26.setSize(1400, 900);
        F26.setVisible(true);
t20.setText("");
t21.setText("");
t22.setText("");






        // TODO add your handling code here:
    }                                         

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {                                          
String s=t20.getText();
String t=t21.getText();
String d=t22.getText();
if(s.length()==0)
    JOptionPane.showMessageDialog(this,"Please Enter The Crime Name");
else if(t.length()==0)
    JOptionPane.showMessageDialog(this,"Please Enter The Country");
else if(d.length()==0)
    JOptionPane.showMessageDialog(this,"Please Enter The Year");
else{
    try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=(Connection)
     DriverManager.getConnection("jdbc:mysql://localhost:3306/cad","root","mysql");
Statement stmt=(Statement) con.createStatement();
String query="insert into sort values(null,'"+s+"','"+t+"','"+d+"');";
stmt.executeUpdate(query);
    }
    catch(Exception m)
 {JOptionPane.showMessageDialog(null, m.getMessage());

}












}





        // TODO add your handling code here:
    }                                         

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F4.setVisible(true);
  F4.setSize(1400, 900);




        // TODO add your handling code here:
    }                                         

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {                                          
t20.setText("");
t21.setText("");
t22.setText("");        // TODO add your handling code here:
    }                                         

    private void t14ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  

        // TODO add your handling code here:
    }                                 

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {                                          
F27.setSize(1400, 900);

        F27.setVisible(true);// TODO add your handling code here:
    }                                         

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JFrame F10;
    private javax.swing.JFrame F11;
    private javax.swing.JFrame F12;
    private javax.swing.JFrame F13;
    private javax.swing.JFrame F14;
    private javax.swing.JFrame F15;
    private javax.swing.JFrame F16;
    private javax.swing.JFrame F17;
    private javax.swing.JFrame F18;
    private javax.swing.JFrame F19;
    private javax.swing.JFrame F2;
    private javax.swing.JFrame F20;
    private javax.swing.JFrame F21;
    private javax.swing.JFrame F22;
    private javax.swing.JFrame F23;
    private javax.swing.JFrame F24;
    private javax.swing.JFrame F25;
    private javax.swing.JFrame F26;
    private javax.swing.JFrame F27;
    private javax.swing.JFrame F3;
    private javax.swing.JFrame F4;
    private javax.swing.JFrame F5;
    private javax.swing.JFrame F6;
    private javax.swing.JFrame F7;
    private javax.swing.JFrame F8;
    private javax.swing.JFrame F9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JPasswordField p3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextArea t9;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextArea ta2;
    private javax.swing.JTable table1;
    // End of variables declaration                   

}
